# Generated by Django 4.1.1 on 2022-09-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
