# Generated by Django 4.1.1 on 2022-09-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='critic1_link',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='album',
            name='critic1_rating',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='album',
            name='critic2_link',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='album',
            name='critic2_rating',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
