# Generated by Django 4.1.1 on 2022-09-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('albums', '0003_album_critic1_link_album_critic1_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='genres.genre'),
        ),
    ]
