# Generated by Django 4.1.1 on 2022-09-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('albums', '0004_album_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(related_name='albums', to='genres.genre'),
        ),
    ]
